### PR TITLE
Bananapi m1

### PR DESCRIPTION
**Pull request by Darmur**
Add recipe for BananaPi M1

### CODE REVIEW

**Comment by RafaelKa** [comment]
@Darmur 
Could you please add the recipe for Banana Pi Pro?
The M1 has no I2S.

**Comment by Darmur** [comment]
unfortunately I don't have this device for testing the recipe locally before pushing it.

is this the device you're referring to?

http://www.lemaker.org/product-bananapro-specification.html

**Comment by RafaelKa** [comment]
> is this the device you're referring to?
> 
> http://www.lemaker.org/product-bananapro-specification.html

Yes it is. And it is supported by armbian see: https://www.armbian.com/banana-pi-pro/

**Comment by RafaelKa** [comment]
@Darmur 
The M1 board i have as well. I tried to build the image for. 
The build was successful and the board boots-up, but there is no possibility to login to myvolumio.
Something is missing in NodeJS/NPM i guess.
Most probably i did something wrong.
Could you please provide the image for M1 board, which I could try?

**Comment by Darmur** [comment]
local builds do not have the proprietary part related to myvolumio

anyhow, you can try this image, I quickly tested it and seems to be working fine.
https://updates.volumio.org/bananapim1/volumio/3.424/Volumio-3.424-2023-01-26-bananapim1.zip

anyhow, this image is provided as-it-is, I made it only for testing purpose

**Comment by Darmur** [comment]
regarding the BananaPi-Pro, I might give it a try and create platform files and recipe, but I won't be able to test it.

**Comment by RafaelKa** [comment]
> local builds do not have the proprietary part related to myvolumio

Also your image is the same, or it has proprietary part?

Is it possible to load the proprietary things to the "Planed" images? So that is the same as for "Raspberry Pi Ltd." devices?

**Comment by Darmur** [comment]
the image I sent is with myvolumio included. I will try to launch official builds from time to time.

**Comment by RafaelKa** [comment]
@Darmur 
Thanks for the image myvolumio login works on that image, but there is no sound on 3.5mm headphone jack.
The sound on jack works on Armbian image v 22.11 Bullseye.

**Comment by Darmur** [comment]
@RafaelKa to enable audio output from the 3.5mm jack, please do the following:

1) enable ssh from the /dev page
2) login into the device with ssh (username: volumio, password: volumio)
3) launch alsamixer
4) press F6 and select "sun4i-codec" card
5) select "Power Amplifier DAC" and "Power Amplifier Mute" and enable them pressing M as shown in the picture below (by default they are muted/disabled)
6) press ESC to exit Alsamixer
7) exit from SSH
8) in Volumio playback options, select "Power Amplifier" as in the "Mixer Control Name" dropdown menu
9) enjoy!

image

**Comment by volumio** [comment]
It would be great to:
- Add a bash script that turns those mixer off by default 
- Populate the cards.json with the right default mixer

**Comment by Darmur** [comment]
cards.json is already updated, the script is a good idea, i'll try to do it (but with low priority)

**Pull request merged**
