### PR TITLE
Aligning pi-uuid with debugger options

### PR DESCRIPTION
**Pull request by foonerd**
Debugger function switch quiet in cmdline.txt missing.

### CODE REVIEW

**Comment by foonerd** [comment]
Please check if further changes are needed.

**Comment by Darmur** [comment]
include userconfig.txt must be declared only on config.txt

please remove the declaration from volumioconfig.txt

please refer to the pi.sh recipe from master branch as a reference for the content of config.txt and volumioconfig.txt
the only changes must be the ones required for nvme on Pi5, the rest must be identical

**Comment by foonerd** [comment]
Remove userconfig reference from volumioconfig file.

**Comment by Darmur** [comment]
now it's OK

**Comment by foonerd** [comment]
Than you for checking, I will mark this pi-uuid as master template until pi changes.

**Pull request merged**
