### PR TITLE
Bump mpd 23.2

### PR DESCRIPTION
**Pull request by volumio**

### CODE REVIEW

**Comment by chourmovs** [comment]
yesss

**Comment by volumio** [comment]
Unfortunately, there appear to be serious regression with this. So we'll revert to previous versions.

Any hint is appreciated if you tested other (newer) versions of mpd and you succesffully compiled them for debian buster

**Comment by chourmovs** [comment]
https://bobrathbone.com/raspberrypi/compiling_mpd.html

in this compilation guide, it's said that anything later than 0.23.5 will not compile on buster because of dependencies... it could be a good start

**Comment by Darmur** [comment]
in the latest beta release 3.536 we managed bump to MPD 0.23.5, many thanks for your hints!

**Pull request merged**
