### PR TITLE
Set up init-v3 on Buster

### PR DESCRIPTION
**Pull request by ashthespy**
Building from @foonerd  and @gkkpch 's work, here are things re-based onto the buster branch.

~Still need to bring in the remainder changes from [foonerd/volumio3-os/tree/init-v3](https://github.com/foonerd/volumio3-os/tree/init-v3).~

### CODE REVIEW

**Comment by ashthespy** [comment]
@foonerd if all looks good, will merge. 
I've taken all your tweaks apart from the `libavfilter-extra libavcodec-extra` codecs). 

Will request you to add this in a new PR and have @Darmur or @volumio  check what needs to be tweaked to get it to work with myVolumio! :-)

**Comment by gkkpch** [comment]
There are some boards which don't have video out, a plymouth theme does not make sense there (nanopi neo/neo2/neo3, more?).

**Comment by Darmur** [comment]
> Some devices still need their theme set, but otherwise I think we are good!
> 
> Device	Base	Arch	`VOLUMIO_DEVICENAME`	Plymouth	Init type
> bananapim1	armv7	armhf	bananapim1		initv3
> bananapipro	armv7	armhf	bananapipro		initv3
> cm4	arm	armhf	cm4	volumio-player	initv3
> mp0	armv7	armhf	mp0		initv3
> mp1	armv7	armhf	mp1	volumio-player	initv3
> nanopiair-armbian	armv7	armhf	nanopiair-armbian		initv3
> nanopim4	armv7	armhf	nanopim4	volumio-player	initv3
> nanopineo2-armbian	armv7	armhf	nanopineo2-armbian		initv3
> nanopineo2-a	armv7	armhf	nanopineo2-a		initv3
> nanopineo2	armv7	armhf	nanopineo2		initv3
> nanopineo3-armbian	armv7	armhf	nanopineo3-armbian		initv3
> nanopineo3	armv7	armhf	nanopineo3		initv3
> nanopineo-armbian	armv7	armhf	nanopineo-armbian		initv3
> odroidc4	armv7	armhf	odroidc4	volumio-player	initv3
> odroidm1s	armv7	armhf	odroidm1s	volumio-player	initv3
> odroidn2	armv7	armhf	odroidn2	volumio-player	initv3
> orangepilite	armv7	armhf	orangepilite		initv3
> orangepione	armv7	armhf	orangepione		initv3
> orangepipc	armv7	armhf	orangepipc		initv3
> pi-kiosk	arm	armhf	pi-kiosk	volumio-player	initv3
> pi	arm	armhf	pi	volumio-player	initv3
> radxa-zero2	armv7	armhf	radxa-zero2	volumio-player	initv3
> radxa-zero	armv7	armhf	radxa-zero	volumio-player	initv3
> rkbox_h96max	armv7	armhf	rkbox_h96max		initv3
> rkbox_hk1	armv7	armhf	rkbox_hk1		initv3
> rkbox_t9	armv7	armhf	rkbox_t9		initv3
> rkbox_x88pro	armv7	armhf	rkbox_x88pro		initv3
> rock-3a	armv7	armhf	rock-3a		initv3
> rockpi-4b	armv7	armhf	rockpi-4b	volumio-player	initv3
> rockpie	armv7	armhf	rockpie		initv3
> rockpis	armv7	armhf	rockpis		initv3
> tinkerboard	armv7	armhf	tinkerboard	volumio-logo	initv3
> vmod-a0	armv7	armhf	vmod-a0		initv3
> x86_amd64	x64	amd64	x86_amd64	volumio-player	initv3

the following devices have HDMI video out capability, they should also have Plymouth set as volumio-player

- bananapim1
- bananapipro
- mp0
- orangepilite
- orangepione
- orangepipc
- rkbox_h96max
- rkbox_hk1
- rkbox_t9
- rkbox_x88pro
- rock-3a

**Comment by ashthespy** [comment]
>There are some boards which don't have video out, a plymouth theme does not make sense there (nanopi neo/neo2/neo3, more?).

Added a new `DISABLE_DISPLAY=yes` flag for such devices, that cleans up `plymouth-lablel` package. TBD what else can be slimmed down. 

For the rest, here is the current overview:

| Device             | `VOLUMIO_DEVICENAME` | Disable Display | Plymouth theme |
| ------------------ | -------------------- | --------------- | -------------- |
| bananapim1         | BananaPi M1          |                 | volumio-player |
| bananapipro        | BananaPi Pro         |                 | volumio-player |
| cm4                | CM4                  |                 | volumio-player |
| mp0                | MP0                  |                 | volumio-player |
| mp1                | Volumio MP1          |                 | volumio-player |
| nanopiair-armbian  | NanoPi Neo Air       | yes             |                |
| nanopim4           | NanoPi M4B           |                 | volumio-player |
| nanopineo2-armbian | NanoPi Neo2          | yes             |                |
| nanopineo2-a       | NanoPi NEO2          | yes             |                |
| nanopineo2         | NanoPi Neo2          | yes             |                |
| nanopineo3-armbian | NanoPi Neo3          | yes             |                |
| nanopineo3         | Nanopi Neo3          | yes             |                |
| nanopineo-armbian  | NanoPi Neo           |                 |                |
| odroidc4           | Odroid-C4            |                 | volumio-player |
| odroidm1s          | Odroid M1S           |                 | volumio-player |
| odroidn2           | Odroid-N2            |                 | volumio-player |
| orangepilite       | Orange Pi Lite       |                 | volumio-player |
| orangepione        | Orange Pi One        |                 | volumio-player |
| orangepipc         | Orange Pi PC         |                 | volumio-player |
| pi-kiosk           | Raspberry Pi         |                 | volumio-player |
| pi                 | Raspberry Pi         |                 | volumio-player |
| radxa-zero2        | Radxa Zero 2         |                 | volumio-player |
| radxa-zero         | Radxa Zero           |                 | volumio-player |
| rkbox_h96max       | RockBox H96Max       |                 | volumio-player |
| rkbox_hk1          | RockBox HK1          |                 | volumio-player |
| rkbox_t9           | RockBox T9           |                 | volumio-player |
| rkbox_x88pro       | RockBox X88Pro 10    |                 | volumio-player |
| rock-3a            | Rock 3A              |                 | volumio-player |
| rockpi-4b          | RockPi 4B            |                 | volumio-player |
| rockpie            | RockPi E             | yes             |                |
| rockpis            | RockPi S             | yes             |                |
| tinkerboard        | Asus Tinkerboard     |                 | volumio-player |
| vmod-a0            | VMOD-A0              |                 |                |
| x86_amd64          | x86_64               |                 | volumio-player |



TBD: What devices need `volumio-logo`?

**Comment by Darmur** [comment]
> > There are some boards which don't have video out, a plymouth theme does not make sense there (nanopi neo/neo2/neo3, more?).
> 
> Added a new `DISABLE_DISPLAY=yes` flag for such devices, that cleans up `plymouth-lablel` package. TBD what else can be slimmed down.
> 
> For the rest, here is the current overview:
> 
> Device	`VOLUMIO_DEVICENAME`	Disable Display	Plymouth theme
> bananapim1	BananaPi M1		volumio-player
> bananapipro	BananaPi Pro		volumio-player
> cm4	CM4		volumio-player
> mp0	MP0		volumio-player
> mp1	Volumio MP1		volumio-player
> nanopiair-armbian	NanoPi Neo Air	yes	
> nanopim4	NanoPi M4B		volumio-player
> nanopineo2-armbian	NanoPi Neo2	yes	
> nanopineo2-a	NanoPi NEO2	yes	
> nanopineo2	NanoPi Neo2	yes	
> nanopineo3-armbian	NanoPi Neo3	yes	
> nanopineo3	Nanopi Neo3	yes	
> nanopineo-armbian	NanoPi Neo		
> odroidc4	Odroid-C4		volumio-player
> odroidm1s	Odroid M1S		volumio-player
> odroidn2	Odroid-N2		volumio-player
> orangepilite	Orange Pi Lite		volumio-player
> orangepione	Orange Pi One		volumio-player
> orangepipc	Orange Pi PC		volumio-player
> pi-kiosk	Raspberry Pi		volumio-player
> pi	Raspberry Pi		volumio-player
> radxa-zero2	Radxa Zero 2		volumio-player
> radxa-zero	Radxa Zero		volumio-player
> rkbox_h96max	RockBox H96Max		volumio-player
> rkbox_hk1	RockBox HK1		volumio-player
> rkbox_t9	RockBox T9		volumio-player
> rkbox_x88pro	RockBox X88Pro 10		volumio-player
> rock-3a	Rock 3A		volumio-player
> rockpi-4b	RockPi 4B		volumio-player
> rockpie	RockPi E	yes	
> rockpis	RockPi S	yes	
> tinkerboard	Asus Tinkerboard		volumio-player
> vmod-a0	VMOD-A0		
> x86_amd64	x86_64		volumio-player
> TBD: What devices need `volumio-logo`?

vmod-a0 also requires "disable display"

**Comment by ashthespy** [comment]
Don't recall, but somehow this has gotten into master, making this dupe

**Pull request closed without merging**
