### PR TITLE
RaspberryPi Tweaks and Kernel bump

### PR DESCRIPTION
**Pull request by ashthespy**
Adds changes proposed in #1 and #2.

### CODE REVIEW

**Comment by volumio** [comment]
Thanks! 
Did you manage to test it and verify the drivers work?

**Comment by ashthespy** [comment]
Nope, don't have any of these dongles..
The changes are again only in the build system, and should be completely transparent to the final image..

**Comment by ashthespy** [comment]
Ah pushed the kernel bump here, if you want to first merge just the refactor in first, let me know.
Wil clean up the commits and add a new PR for just the kernel bump.

**Comment by volumio** [comment]
I run it against latest PI kernel, but it failed (first for a kernel rev that Mr engman did not build yet) then for a missing file:

[ ---- ] Installed Node v14.15.4 arm_version: 6
[ -- ] Blocking nodejs updgrades for 14.18.1
[ ---- ] Adding Custom DAC firmware from github
https://raw.githubusercontent.com/hftsai256/wm8960-rpi-modules/main/wm8960-modules-rpi-5.10.73.tar.gz:
2021-11-04 20:45:54 ERROR 404: Not Found.
[ error ] Failed to get firmware: [ wm8960 ]
2021-11-04 20:45:55 URL:https://codeload.github.com/allocom/piano-firmware/tar.gz/master [26930] -> "AlloPiano.tar.gz" [1]
2021-11-04 20:45:55 URL:https://codeload.github.com/taudac/modules/tar.gz/rpi-volumio-5.10.73-taudac-modules [59364] -> "TauDAC.tar.gz" [1]
2021-11-04 20:45:56 URL:https://raw.githubusercontent.com/Darmur/bassowl-hat/master/driver/archives/modules-rpi-5.10.73-bassowl.tar.gz [16512/16512] -> "Bassowl.tar.gz" [1]
[ ---- ] Installing additional wireless drivers. Many thanks MrEngman! [ 8188eu 8188fu 8192eu 8812au 8821cu 8822bu ]
/tmp/wifi /
[ -- ] [arm-v7l] Fetching driver [ 8188eu ]
[ -- ] [arm-v7l] Installed [ ok ]
[ -- ] [arm-v7] Fetching driver [ 8188eu ]
[ -- ] [arm-v7] Installed [ ok ]
[ -- ] [arm] Fetching driver [ 8188eu ]
[ -- ] [arm] Installed [ ok ]
[ -- ] [arm-v7l] Fetching driver [ 8188fu ]
/bin/mv: cannot stat '8188fu.conf': No such file or directory
[ error ] Volumio chroot config failed [ chrootconfig.sh ]
[ error ] Error stack [device_chroot_tweaks_pre] <= [main] <=  [ 118 /chroot_device_config.sh ]
[ error ] Imagebuilder script failed!!
[ error ] Error stack [source] <= [main] <=  [ 228 /home/mi/Build/scripts/makeimage.sh ]
[ -- ] Cleaning up image_tmp mounts
[ -- ] Unmounting chroot temporary devices at /mnt/volumio/rootfs
[ .. ] Cleaning loop device /dev/loop0 [ /dev/loop0: [2306]:6956203 (/home/mi/Build/Build_2021-11-04_21-35_root/Volumiobuster-3.133-2021-11-04-pi.img) ]
[ .. ] Deleting image file
[ error ] BUILD FAILED
[ error ] Rembuilder script failed!! [ Line build ]
[ .. ] Removing lock file...
[ .. ] Build terminated... [ 12:20 min ]


This shall be fixed in a way it does not fail on fetching wireless drivers if non-existent

**Comment by ashthespy** [comment]
That should be a bit more robust.. There are a quite a few workarounds for different failure cases!

**Comment by ashthespy** [comment]
PS: Squash and merge when all is good!

**Pull request merged**
