### PR TITLE
Addidtions for primo detection

### PR DESCRIPTION
**Pull request by mervinderuiter**

### CODE REVIEW

**Comment by ashthespy** [comment]
Are you sure you have this in the right place?

**Comment by volumio** [comment]
@ashthespy do you think it should be in a different place?

**Comment by ashthespy** [comment]
Essentially here you consider every tinkerboard a primo.  Since I don't have one, I never got around to "porting" the primo into it's own device. Ideally, you want mimic https://github.com/volumio/Build/pull/375 and create a proper recipe for Primo hardware. 

This also makes all these checks over at [`alsa_controller/index.js`](https://github.com/volumio/volumio3-backend/blob/0bcd69ed74c81b6fbbb3f928c3d20b44dd5f4ee4/app/plugins/audio_interface/alsa_controller/index.js#L1156-L1169) much more cleaner and straightforward. You would just need to call test for  `getSystemVersion().hardware`

**Comment by mervinderuiter** [comment]
@ashthespy You are right, but for now we leave it here. We can port it later.

**Comment by volumio** [comment]
@ashthespy you are right. But for the sake of simplicity, we'll do that as it is (to keep backward compatibility).
We will use the strategy you suggest for the next Volumio products

**Comment by ashthespy** [comment]
> But for the sake of simplicity, we'll do that as it is (to keep backward compatibility).

Sure, just be aware that this isn't really backwards compatible..

From [here](https://github.com/volumio/Build/blob/dd2a4339faaeb892c7f467e7dc8d424aefb0bd03/build.sh#L73) and [here](https://github.com/volumio/Build/blob/dd2a4339faaeb892c7f467e7dc8d424aefb0bd03/build.sh#L367-L369)
```bash
  primo) echo 'Writing Primo Image File'
    check_os_release "armv7" "$VERSION" "$DEVICE"
    sh scripts/primoimage.sh -v "$VERSION" -p "$PATCH" -a armv7
```
So previously you'd call `build.sh <> -d primo` and have an image called `"Volumio${VERSION}-${BUILDDATE}-primo.img"`.
And that image would also have `VOLUMIO_HARDWARE=primo` 



When you eventually do want to switch, have a look at any of the [`kvim{1,2,3}`](https://github.com/volumio/volumio3-os/blob/master/recipes/devices/kvim2.sh) devices to see how it could be done with minimal repetitions..

**Pull request merged**
